// lib/quyen-config.ts — dùng được cả client và server
export const DEFAULT_QUYEN: Record<string, boolean> = {
  don_hang_xem: true,
  don_hang_tao: true,
  don_hang_sua: true,
  don_hang_huy: false,
  don_hang_xoa: false,
  khach_hang: true,
  giao_hang: true,
  doi_soat: true,
  san_pham_xem: true,
  san_pham_sua: false,
  kho_nhap: true,
  kho_kiem: true,
  xu_ly_hang: true,
  dat_hang_ncc: true,
  nha_cung_cap_xem: true,
  thanh_toan_ncc: false,
  ct_km_tao: true,
  ct_km_sua_xoa: false,
  thu_chi: true,
  bao_cao: false,
  nhan_su_xem: true,
  cham_cong: true,
  tam_ung: true,
  chi_tra_luong: false,
  nhat_ky: false,
  tai_khoan: false,
}

export const QUYEN_LABELS: Record<string, string> = {
  don_hang_xem:     '📋 Xem danh sách đơn hàng',
  don_hang_tao:     '➕ Tạo đơn hàng mới',
  don_hang_sua:     '✏️ Sửa đơn hàng',
  don_hang_huy:     '🚫 Hủy đơn hàng',
  don_hang_xoa:     '🗑️ Xóa đơn hàng',
  khach_hang:       '👥 Quản lý khách hàng',
  giao_hang:        '🚚 Tạo chuyến giao hàng',
  doi_soat:         '💰 Đối soát giao hàng',
  san_pham_xem:     '📦 Xem sản phẩm & tồn kho',
  san_pham_sua:     '✏️ Sửa/xóa sản phẩm',
  kho_nhap:         '📥 Nhập kho',
  kho_kiem:         '🔍 Kiểm kho',
  xu_ly_hang:       '🔧 Xử lý hàng lỗi',
  dat_hang_ncc:     '🛒 Đặt hàng NCC',
  nha_cung_cap_xem: '🏭 Xem nhà cung cấp',
  thanh_toan_ncc:   '💳 Thanh toán NCC',
  ct_km_tao:        '🎁 Tạo chương trình KM',
  ct_km_sua_xoa:    '✏️ Sửa/xóa chương trình KM',
  thu_chi:          '💵 Thêm/sửa thu chi',
  bao_cao:          '📊 Xem báo cáo tài chính',
  nhan_su_xem:      '👤 Xem nhân viên',
  cham_cong:        '🕐 Chấm công',
  tam_ung:          '💸 Ghi tạm ứng',
  chi_tra_luong:    '💰 Chi trả lương NV',
  nhat_ky:          '📋 Xem nhật ký thao tác',
  tai_khoan:        '⚙️ Quản lý tài khoản',
}

export const QUYEN_GROUPS = [
  { label: '🛒 Bán hàng', keys: ['don_hang_xem','don_hang_tao','don_hang_sua','don_hang_huy','don_hang_xoa','khach_hang'] },
  { label: '🚚 Giao hàng & Đối soát', keys: ['giao_hang','doi_soat'] },
  { label: '📦 Kho & Hàng hóa', keys: ['san_pham_xem','san_pham_sua','kho_nhap','kho_kiem','xu_ly_hang','dat_hang_ncc','nha_cung_cap_xem','ct_km_tao','ct_km_sua_xoa'] },
  { label: '💰 Tài chính', keys: ['thu_chi','thanh_toan_ncc','bao_cao','chi_tra_luong'] },
  { label: '👤 Nhân sự', keys: ['nhan_su_xem','cham_cong','tam_ung'] },
  { label: '⚙️ Quản trị', keys: ['nhat_ky','tai_khoan'] },
]
